owner: duyet
repo: uptime

sites:
  - name: duyet.net  
    url: https://duyet.net
  - name: blog.duyet.net  
    url: https://blog.duyet.net
  - name: s.duyet.net
    url: https://s.duyet.net
  - name: pricetrack
    url: https://tracker.duyet.net
  - name: cdn.duyet.net
    url: https://cdn.duyet.net
  - name: til.duyet.net
    url: https://til.duyet.net
  - name: Okie.one
    url: https://okie.one
  - name: The Feedback
    url: https://feedback.okie.one
  - name: The Feedback Docs
    url: https://feedback.okie.one/docs
  - name: Ngan.vn
    url: https://cake.ngan.vn
  - name: Very Nini
    url: https://verynini.com
  - name: hocdata.com
    url: https://hocdata.com
  - name: uptime
    url: https://duyet.github.io/uptime

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Uptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is the page which uses **real-time** data from [GitHub repository](https://github.com/duyet/uptime).
  navbar:
    - title: Status
      href: https://$OWNER.github.io/$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
